### ISSUE TITLE
Feature Request: Enforce query size limit

### ISSUE THREAD

**Issue by lordnynex** [jbochi/lua-resty-cassandra#51] opened 2015-03-29 23:01 UTC
It seems cassandra has some sort of max query size?

I'm performing a very large WHERE IN () and it appears the query is being truncated consistently which throws a syntax error. 

Cassandra returned error (Syntax_error): \"line 1:6116 no viable alternative at input ')' (...

I'm not sure what this limit is but it would be nice if the driver knew about it.

**Comment by jbochi** [comment] 2015-03-30 12:23
Hi Brandon,

The frame is limited by the protocol in 256MB. Is it possible that you are
hitting this limit? How many elements and of which type are you using in
the WHERE IN clause?


On Sun, Mar 29, 2015, 8:01 PM Brandon B <notifications@github.com> wrote:

It seems cassandra has some sort of max query size?

I'm performing a very large WHERE IN () and it appears the query is being
truncated consistently which throws a syntax error.

Cassandra returned error (Syntax_error): \"line 1:6116 no viable
alternative at input ')' (...

I'm not sure what this limit is but it would be nice if the driver knew
about it.

—
Reply to this email directly or view it on GitHub
<https://github.com/jbochi/lua-resty-cassandra/issues/51>.<img src="
https://ci5.googleusercontent.com/proxy/p-nU006DJvPIXZZRbd-LLHFOfCHjm6T71CPOGxBE7ATRb28JMFsl6AwbO-ObYymnlm9HaPWINvewBfylqPZqD0LMTkZqKfwg7JiahRrzcjtpX8ZFjciGTNJxgQkN_MxKKXjgLCB5a_OIhh95RYlUqk9buXN8Qw=s0-d-e1-ft#https://github.com/notifications/beacon/AAR3aByHVE2vvxQkH5AGL6vld5XoCReEks5n6HvfgaJpZM4D2wYb.gif
">

**Comment by lordnynex** [comment] 2015-03-30 20:27
I believe this is a malformed query on my side. In the end the fix was to break the WHERE IN clause into multiple select's. I wish I had more time to chase this down, but the IN clause was around 1000 arguments. 

I was thinking, it would be beneficial to my current and future work if I can pass a tailored object to bind params on select. Similar to :execute("INSERT INTO ...(some_set) VALUES(?)", { cassandra.set){}).

**Comment by jbochi** [comment] 2015-03-30 23:12
Sorry, I am not sure I understood your suggestion correctly. Do you mean named arguments like #28?

Could you please elaborate?

Anyway, I will close this issue for now. Please feel free to open it again if you are able to reproduce the issue.

**Closed by jbochi** 2015-03-30 23:12 UTC

**Comment by lordnynex** [comment] 2015-03-30 23:24
I want to use bind params on a large WHERE IN SET. As opposed to writing 'WHERE IN(?, ?, ?, ?, ?........)

I'd like to write something like
c:execute("SELECT id FROM table WHERE id IN(?)", { cassandra.whereIn({ flat table of values}))

**Comment by thibaultCha** [comment] 2015-03-30 23:54
You can already do this @lordnynex. A `IN` is a `cassandra.list` iirc.

So you can have 

```
c:execute("SELECT id FROM table WHERE id IN ?", { cassandra.list({"foo", "bar"}))
```

**Comment by lordnynex** [comment] 2015-03-30 23:57
Oh awesome. I'll give it a shot. I was under the impression that cassandra.list was the equivalent of { '', '' } which seemed in-congruent with the where in syntax.

**Comment by thibaultCha** [comment] 2015-03-30 23:58
If not, give a try to one of the other type. I am 100% sure this is possible because I did it in the past, don't remember which type/syntax combination tho.

**Comment by jbochi** [comment] 2015-03-31 13:02
@lordnynex, @thibaultCha is right, you can use `cassandra.list` for that. There is an example in the specs: https://github.com/jbochi/lua-resty-cassandra/blob/master/spec/functional_spec.lua#L170
